export const mockBooks = [
  {
    id: 'readify-001',
    title: 'Nhà Giả Kim',
    author: 'Paulo Coelho',
    category: 'Tiểu thuyết',
    price: 129000,
    discountPrice: 99000,
    rating: 4.8,
    sold: 1520,
    publisher: 'Nhà Xuất Bản Hội Nhà Văn',
    series: 'Tác phẩm kinh điển hiện đại',
    image: 'https://via.placeholder.com/400x560.png?text=Nha+Gia+Kim',
  },
  {
    id: 'readify-002',
    title: 'Cây Cam Ngọt Của Tôi',
    author: 'José Mauro de Vasconcelos',
    category: 'Văn học nước ngoài',
    price: 118000,
    discountPrice: 89000,
    rating: 4.9,
    sold: 1875,
    publisher: 'Nhã Nam',
    series: 'Tủ sách văn học cảm xúc',
    image: 'https://via.placeholder.com/400x560.png?text=Cay+Cam+Ngot+Cua+Toi',
  },
  {
    id: 'readify-003',
    title: 'Tâm Lý Học Về Tiền',
    author: 'Morgan Housel',
    category: 'Kinh tế',
    price: 169000,
    discountPrice: 135000,
    rating: 4.7,
    sold: 2140,
    publisher: 'Nhà Xuất Bản Dân Trí',
    series: 'Tài chính cá nhân',
    image: 'https://via.placeholder.com/400x560.png?text=Tam+Ly+Hoc+Ve+Tien',
  },
  {
    id: 'readify-004',
    title: 'Atomic Habits - Thay Đổi Tí Hon Hiệu Quả Bất Ngờ',
    author: 'James Clear',
    category: 'Kỹ năng sống',
    price: 198000,
    discountPrice: 159000,
    rating: 4.9,
    sold: 2680,
    publisher: 'Nhà Xuất Bản Thế Giới',
    series: 'Phát triển bản thân',
    image: 'https://via.placeholder.com/400x560.png?text=Atomic+Habits',
  },
  {
    id: 'readify-005',
    title: 'Muôn Kiếp Nhân Sinh',
    author: 'Nguyên Phong',
    category: 'Tâm linh',
    price: 186000,
    discountPrice: 149000,
    rating: 4.8,
    sold: 2410,
    publisher: 'First News',
    series: 'Muôn kiếp nhân sinh',
    image: 'https://via.placeholder.com/400x560.png?text=Muon+Kiep+Nhan+Sinh',
  },
  {
    id: 'readify-006',
    title: 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
    author: 'Rosie Nguyễn',
    category: 'Kỹ năng sống',
    price: 96000,
    discountPrice: 79000,
    rating: 4.6,
    sold: 3250,
    publisher: 'Nhà Xuất Bản Hội Nhà Văn',
    series: 'Sống đẹp mỗi ngày',
    image: 'https://via.placeholder.com/400x560.png?text=Tuoi+Tre+Dang+Gia+Bao+Nhieu',
  },
  {
    id: 'readify-007',
    title: 'Lược Sử Loài Người',
    author: 'Yuval Noah Harari',
    category: 'Lịch sử',
    price: 245000,
    discountPrice: 199000,
    rating: 4.8,
    sold: 1430,
    publisher: 'Nhã Nam',
    series: 'Sapiens',
    image: 'https://via.placeholder.com/400x560.png?text=Luoc+Su+Loai+Nguoi',
  },
  {
    id: 'readify-008',
    title: 'Đắc Nhân Tâm',
    author: 'Dale Carnegie',
    category: 'Kỹ năng sống',
    price: 110000,
    discountPrice: 85000,
    rating: 4.7,
    sold: 4120,
    publisher: 'First News',
    series: 'Nghệ thuật ứng xử',
    image: 'https://via.placeholder.com/400x560.png?text=Dac+Nhan+Tam',
  },
  {
    id: 'readify-009',
    title: 'Không Gia Đình',
    author: 'Hector Malot',
    category: 'Thiếu nhi',
    price: 132000,
    discountPrice: 104000,
    rating: 4.5,
    sold: 960,
    publisher: 'Nhà Xuất Bản Kim Đồng',
    series: 'Tủ sách thiếu nhi kinh điển',
    image: 'https://via.placeholder.com/400x560.png?text=Khong+Gia+Dinh',
  },
  {
    id: 'readify-010',
    title: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ',
    author: 'Nguyễn Nhật Ánh',
    category: 'Văn học Việt Nam',
    price: 89000,
    discountPrice: 69000,
    rating: 4.8,
    sold: 2790,
    publisher: 'Nhà Xuất Bản Trẻ',
    series: 'Nguyễn Nhật Ánh',
    image: 'https://via.placeholder.com/400x560.png?text=Cho+Toi+Xin+Mot+Ve+Di+Tuoi+Tho',
  },
  {
    id: 'readify-011',
    title: 'Hành Tinh Của Một Kẻ Nghĩ Nhiều',
    author: 'Amanda Huỳnh',
    category: 'Tản văn',
    price: 108000,
    discountPrice: 86000,
    rating: 4.4,
    sold: 1345,
    publisher: 'Nhà Xuất Bản Thế Giới',
    series: 'Chữa lành tâm hồn',
    image: 'https://via.placeholder.com/400x560.png?text=Hanh+Tinh+Cua+Mot+Ke+Nghi+Nhieu',
  },
  {
    id: 'readify-012',
    title: 'Thiên Tài Bên Trái, Kẻ Điên Bên Phải',
    author: 'Cao Minh',
    category: 'Tâm lý',
    price: 148000,
    discountPrice: 119000,
    rating: 4.6,
    sold: 1760,
    publisher: 'Nhà Xuất Bản Văn Học',
    series: 'Khám phá tâm trí',
    image: 'https://via.placeholder.com/400x560.png?text=Thien+Tai+Ben+Trai',
  },
  {
    id: 'readify-013',
    title: 'Dám Bị Ghét',
    author: 'Kishimi Ichiro',
    category: 'Kỹ năng sống',
    price: 138000,
    discountPrice: 109000,
    rating: 4.7,
    sold: 2085,
    publisher: 'Nhã Nam',
    series: 'Phát triển bản thân',
    image: 'https://via.placeholder.com/400x560.png?text=Dam+Bi+Ghet',
  },
  {
    id: 'readify-014',
    title: 'Lập Trình Cho Người Mới Bắt Đầu Với JavaScript',
    author: 'Phạm Minh Tuấn',
    category: 'Công nghệ',
    price: 215000,
    discountPrice: 178000,
    rating: 4.5,
    sold: 720,
    publisher: 'Nhà Xuất Bản Thông Tin Và Truyền Thông',
    series: 'Học công nghệ cùng Readify',
    image: 'https://via.placeholder.com/400x560.png?text=JavaScript+Can+Ban',
  },
];

export const priceBounds = mockBooks.reduce(
  (bounds, book) => {
    const effectivePrice = book.discountPrice ?? book.price;

    return {
      min: Math.min(bounds.min, effectivePrice),
      max: Math.max(bounds.max, book.price),
    };
  },
  { min: Infinity, max: -Infinity }
);

export const getFilterOptions = (books = mockBooks) => {
  const uniqueSortedValues = (key) =>
    [...new Set(books.map((book) => book[key]).filter(Boolean))].sort((a, b) =>
      a.localeCompare(b, 'vi')
    );

  return {
    categories: uniqueSortedValues('category'),
    authors: uniqueSortedValues('author'),
    series: uniqueSortedValues('series'),
    publishers: uniqueSortedValues('publisher'),
  };
};

export const defaultFilterState = (bounds = priceBounds) => ({
  search: '',
  categories: [],
  priceRange: [bounds.min, bounds.max],
  rating: null,
  authors: [],
  series: [],
  publishers: [],
});